/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onlyoffice_DocBuilderValue */

#ifndef _Included_com_onlyoffice_DocBuilderValue
#define _Included_com_onlyoffice_DocBuilderValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    allocate0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_allocate0__
  (JNIEnv *, jclass);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    allocate0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_allocate0__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    allocate0
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_allocate0__Z
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    allocate0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_allocate0__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    allocate0
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_allocate0__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    allocate0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_allocate0__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    free0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderValue_free0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    clear0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderValue_clear0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isEmpty0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isEmpty0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isNull0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isNull0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isUndefined0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isUndefined0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isBoolean0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isBoolean0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isInt0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isInt0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isDouble0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isDouble0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isString0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isString0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isFunction0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isFunction0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isObject0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isObject0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isArray0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isArray0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    isTypedArray0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_isTypedArray0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    getLength0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_onlyoffice_DocBuilderValue_getLength0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    toBool0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderValue_toBool0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    toInt0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_onlyoffice_DocBuilderValue_toInt0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    toDouble0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_onlyoffice_DocBuilderValue_toDouble0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    toString0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onlyoffice_DocBuilderValue_toString0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    getProperty0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_getProperty0
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    get0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_get0__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    get0
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_get0__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    setProperty0
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderValue_setProperty0
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    set0
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderValue_set0__JLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    set0
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderValue_set0__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    createUndefined0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_createUndefined0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    createNull0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_createNull0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    call0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_call0__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    call0
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_call0__JLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    call0
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_call0__JLjava_lang_String_2JJ
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    call0
 * Signature: (JLjava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_call0__JLjava_lang_String_2JJJ
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    call0
 * Signature: (JLjava/lang/String;JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_call0__JLjava_lang_String_2JJJJ
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong, jlong, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    call0
 * Signature: (JLjava/lang/String;JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_call0__JLjava_lang_String_2JJJJJ
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderValue
 * Method:    call0
 * Signature: (JLjava/lang/String;JJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderValue_call0__JLjava_lang_String_2JJJJJJ
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
