/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onlyoffice_DocBuilderInitializer */

#ifndef _Included_com_onlyoffice_DocBuilderInitializer
#define _Included_com_onlyoffice_DocBuilderInitializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onlyoffice_DocBuilderInitializer
 * Method:    initialize0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderInitializer_initialize0__
  (JNIEnv *, jclass);

/*
 * Class:     com_onlyoffice_DocBuilderInitializer
 * Method:    initialize0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderInitializer_initialize0__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
