/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onlyoffice_DocBuilderContext */

#ifndef _Included_com_onlyoffice_DocBuilderContext
#define _Included_com_onlyoffice_DocBuilderContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    free0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderContext_free0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    createUndefined0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderContext_createUndefined0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    createNull0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderContext_createNull0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    createObject0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderContext_createObject0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    createArray0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderContext_createArray0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    createTypedArray0
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderContext_createTypedArray0
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    createGlobal0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderContext_createGlobal0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    createScope0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_onlyoffice_DocBuilderContext_createScope0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderContext
 * Method:    isError0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onlyoffice_DocBuilderContext_isError0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
