/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onlyoffice_DocBuilderContextScope */

#ifndef _Included_com_onlyoffice_DocBuilderContextScope
#define _Included_com_onlyoffice_DocBuilderContextScope
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onlyoffice_DocBuilderContextScope
 * Method:    free0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderContextScope_free0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onlyoffice_DocBuilderContextScope
 * Method:    close0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_onlyoffice_DocBuilderContextScope_close0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
